import { NextRequest, NextResponse } from 'next/server';

// Mock MLS data with Denver metro area properties
const mockMLSData = [
  // Original properties
  {
    address: "123 Main St",
    city: "Denver",
    state: "CO",
    zip: "80202",
    price: "$500,000",
    beds: 3,
    baths: 2,
    sqft: 1800,
    status: "Active",
    mlsId: "MLS123456",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "456 Oak Ave",
    city: "Aurora",
    state: "CO",
    zip: "80012",
    price: "$750,000",
    beds: 4,
    baths: 3,
    sqft: 2500,
    status: "Pending",
    mlsId: "MLS654321",
    salesPitch: "Beautifully maintained 4-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  // Denver metro area properties
  {
    address: "1234 Larimer St",
    city: "Denver",
    state: "CO",
    zip: "80202",
    price: "$425,000",
    beds: 2,
    baths: 2,
    sqft: 1200,
    status: "Active",
    mlsId: "MLS100001",
    salesPitch: "Cozy 2-bedroom condo in a prime location. Close to downtown, parks, and public transportation. Perfect for first-time homebuyers or investors."
  },
  {
    address: "5678 Colfax Ave",
    city: "Lakewood",
    state: "CO",
    zip: "80214",
    price: "$675,000",
    beds: 3,
    baths: 2,
    sqft: 1850,
    status: "Active",
    mlsId: "MLS100002",
    salesPitch: "Modern 3-bedroom townhome with a private backyard. Features a large kitchen, open floor plan, and a convenient location."
  },
  {
    address: "9012 Broadway",
    city: "Englewood",
    state: "CO",
    zip: "80113",
    price: "$890,000",
    beds: 4,
    baths: 3,
    sqft: 2800,
    status: "Active",
    mlsId: "MLS100003",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "3456 Speer Blvd",
    city: "Denver",
    state: "CO",
    zip: "80211",
    price: "$550,000",
    beds: 2,
    baths: 2,
    sqft: 1400,
    status: "Pending",
    mlsId: "MLS100004",
    salesPitch: "Charming 2-bedroom condo with a modern kitchen and a spacious living area. Perfect for a small family or a professional."
  },
  {
    address: "7890 Alameda Ave",
    city: "Lakewood",
    state: "CO",
    zip: "80226",
    price: "$725,000",
    beds: 3,
    baths: 2,
    sqft: 1950,
    status: "Active",
    mlsId: "MLS100005",
    salesPitch: "Spacious 3-bedroom home with a large backyard. Features a modern kitchen, open floor plan, and a convenient location."
  },
  {
    address: "2345 Colorado Blvd",
    city: "Denver",
    state: "CO",
    zip: "80207",
    price: "$625,000",
    beds: 3,
    baths: 2,
    sqft: 1750,
    status: "Active",
    mlsId: "MLS100006",
    salesPitch: "Cozy 3-bedroom home with a modern kitchen and a spacious living area. Perfect for a small family or a professional."
  },
  {
    address: "6789 Evans Ave",
    city: "Denver",
    state: "CO",
    zip: "80222",
    price: "$475,000",
    beds: 2,
    baths: 1,
    sqft: 1100,
    status: "Active",
    mlsId: "MLS100007",
    salesPitch: "Charming 2-bedroom condo with a modern kitchen and a spacious living area. Perfect for a small family or a professional."
  },
  {
    address: "1122 Hampden Ave",
    city: "Denver",
    state: "CO",
    zip: "80231",
    price: "$825,000",
    beds: 4,
    baths: 3,
    sqft: 2600,
    status: "Active",
    mlsId: "MLS100008",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "3344 Mississippi Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$575,000",
    beds: 3,
    baths: 2,
    sqft: 1650,
    status: "Pending",
    mlsId: "MLS100009",
    salesPitch: "Cozy 3-bedroom home with a modern kitchen and a spacious living area. Perfect for a small family or a professional."
  },
  {
    address: "5566 Yale Ave",
    city: "Denver",
    state: "CO",
    zip: "80204",
    price: "$695,000",
    beds: 3,
    baths: 2,
    sqft: 1900,
    status: "Active",
    mlsId: "MLS100010",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "7788 Iliff Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$525,000",
    beds: 2,
    baths: 2,
    sqft: 1350,
    status: "Active",
    mlsId: "MLS100011",
    salesPitch: "Beautifully maintained 2-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "9900 Parker Rd",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$775,000",
    beds: 4,
    baths: 3,
    sqft: 2400,
    status: "Active",
    mlsId: "MLS100012",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "1111 Arapahoe Rd",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$925,000",
    beds: 4,
    baths: 3,
    sqft: 2900,
    status: "Active",
    mlsId: "MLS100013",
    salesPitch: "Charming 4-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "2222 Belleview Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$625,000",
    beds: 3,
    baths: 2,
    sqft: 1800,
    status: "Pending",
    mlsId: "MLS100014",
    salesPitch: "Beautifully maintained 3-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "3333 Dartmouth Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$725,000",
    beds: 3,
    baths: 2,
    sqft: 2000,
    status: "Active",
    mlsId: "MLS100015",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "4444 Evans Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$475,000",
    beds: 2,
    baths: 1,
    sqft: 1150,
    status: "Active",
    mlsId: "MLS100016",
    salesPitch: "Beautifully maintained 2-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "5555 Florida Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$675,000",
    beds: 3,
    baths: 2,
    sqft: 1850,
    status: "Active",
    mlsId: "MLS100017",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "6666 Girard Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$825,000",
    beds: 4,
    baths: 3,
    sqft: 2500,
    status: "Active",
    mlsId: "MLS100018",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "7777 Holly St",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$575,000",
    beds: 3,
    baths: 2,
    sqft: 1700,
    status: "Pending",
    mlsId: "MLS100019",
    salesPitch: "Beautifully maintained 3-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "8888 Jewell Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$725,000",
    beds: 3,
    baths: 2,
    sqft: 1950,
    status: "Active",
    mlsId: "MLS100020",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "9999 Kentucky Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$525,000",
    beds: 2,
    baths: 2,
    sqft: 1400,
    status: "Active",
    mlsId: "MLS100021",
    salesPitch: "Beautifully maintained 2-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "1111 Leetsdale Dr",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$875,000",
    beds: 4,
    baths: 3,
    sqft: 2700,
    status: "Active",
    mlsId: "MLS100022",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "2222 Monaco Pkwy",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$625,000",
    beds: 3,
    baths: 2,
    sqft: 1750,
    status: "Active",
    mlsId: "MLS100023",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "3333 Oneida St",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$475,000",
    beds: 2,
    baths: 1,
    sqft: 1200,
    status: "Pending",
    mlsId: "MLS100024",
    salesPitch: "Beautifully maintained 2-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "4444 Quebec St",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$775,000",
    beds: 4,
    baths: 3,
    sqft: 2300,
    status: "Active",
    mlsId: "MLS100025",
    salesPitch: "Charming 4-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "5555 Rampart Way",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$925,000",
    beds: 4,
    baths: 3,
    sqft: 2800,
    status: "Active",
    mlsId: "MLS100026",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "6666 Sheridan Blvd",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$675,000",
    beds: 3,
    baths: 2,
    sqft: 1900,
    status: "Active",
    mlsId: "MLS100027",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "7777 Tamarac Dr",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$575,000",
    beds: 3,
    baths: 2,
    sqft: 1650,
    status: "Pending",
    mlsId: "MLS100028",
    salesPitch: "Beautifully maintained 3-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "8888 Union Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$725,000",
    beds: 3,
    baths: 2,
    sqft: 2000,
    status: "Active",
    mlsId: "MLS100029",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "9999 Wadsworth Blvd",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$825,000",
    beds: 4,
    baths: 3,
    sqft: 2400,
    status: "Active",
    mlsId: "MLS100030",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "1111 Zuni St",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$525,000",
    beds: 2,
    baths: 2,
    sqft: 1350,
    status: "Active",
    mlsId: "MLS100031",
    salesPitch: "Beautifully maintained 2-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "2222 1st Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$675,000",
    beds: 3,
    baths: 2,
    sqft: 1850,
    status: "Pending",
    mlsId: "MLS100032",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "3333 2nd Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$775,000",
    beds: 4,
    baths: 3,
    sqft: 2200,
    status: "Active",
    mlsId: "MLS100033",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "4444 3rd Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$475,000",
    beds: 2,
    baths: 1,
    sqft: 1100,
    status: "Active",
    mlsId: "MLS100034",
    salesPitch: "Beautifully maintained 2-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "5555 4th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$625,000",
    beds: 3,
    baths: 2,
    sqft: 1700,
    status: "Active",
    mlsId: "MLS100035",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "6666 5th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$875,000",
    beds: 4,
    baths: 3,
    sqft: 2600,
    status: "Pending",
    mlsId: "MLS100036",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "7777 6th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$725,000",
    beds: 3,
    baths: 2,
    sqft: 1950,
    status: "Active",
    mlsId: "MLS100037",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "8888 7th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$575,000",
    beds: 3,
    baths: 2,
    sqft: 1600,
    status: "Active",
    mlsId: "MLS100038",
    salesPitch: "Beautifully maintained 3-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "9999 8th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$825,000",
    beds: 4,
    baths: 3,
    sqft: 2500,
    status: "Active",
    mlsId: "MLS100039",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "1111 9th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$675,000",
    beds: 3,
    baths: 2,
    sqft: 1800,
    status: "Pending",
    mlsId: "MLS100040",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "2222 10th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$525,000",
    beds: 2,
    baths: 2,
    sqft: 1400,
    status: "Active",
    mlsId: "MLS100041",
    salesPitch: "Beautifully maintained 2-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "3333 11th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$775,000",
    beds: 4,
    baths: 3,
    sqft: 2300,
    status: "Active",
    mlsId: "MLS100042",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "4444 12th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$925,000",
    beds: 4,
    baths: 3,
    sqft: 2900,
    status: "Active",
    mlsId: "MLS100043",
    salesPitch: "Charming 4-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "5555 13th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$625,000",
    beds: 3,
    baths: 2,
    sqft: 1750,
    status: "Pending",
    mlsId: "MLS100044",
    salesPitch: "Beautifully maintained 3-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "6666 14th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$725,000",
    beds: 3,
    baths: 2,
    sqft: 2000,
    status: "Active",
    mlsId: "MLS100045",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "7777 15th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$475,000",
    beds: 2,
    baths: 1,
    sqft: 1200,
    status: "Active",
    mlsId: "MLS100046",
    salesPitch: "Beautifully maintained 2-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "8888 16th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$675,000",
    beds: 3,
    baths: 2,
    sqft: 1850,
    status: "Active",
    mlsId: "MLS100047",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "9999 17th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$825,000",
    beds: 4,
    baths: 3,
    sqft: 2400,
    status: "Pending",
    mlsId: "MLS100048",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "1111 18th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$575,000",
    beds: 3,
    baths: 2,
    sqft: 1650,
    status: "Active",
    mlsId: "MLS100049",
    salesPitch: "Charming 3-bedroom home in the heart of Denver! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "2222 19th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$725,000",
    beds: 3,
    baths: 2,
    sqft: 1950,
    status: "Active",
    mlsId: "MLS100050",
    salesPitch: "Beautifully maintained 3-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "3333 20th Ave",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: "$875,000",
    beds: 4,
    baths: 3,
    sqft: 2700,
    status: "Active",
    mlsId: "MLS100051",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  // --- BEGIN GENERATED MOCK PROPERTIES ---
  // California
  {
    address: "1001 Sunset Blvd",
    city: "Los Angeles",
    state: "CA",
    zip: "90026",
    price: "$1,250,000",
    beds: 4,
    baths: 3,
    sqft: 2200,
    status: "Active",
    mlsId: "MLSCA0001",
    salesPitch: "Modern 4-bedroom home in a prime location. Close to downtown, parks, and public transportation. Perfect for first-time homebuyers or investors."
  },
  {
    address: "2002 Market St",
    city: "San Francisco",
    state: "CA",
    zip: "94114",
    price: "$1,800,000",
    beds: 3,
    baths: 2,
    sqft: 1800,
    status: "Pending",
    mlsId: "MLSCA0002",
    salesPitch: "Beautifully maintained 3-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  {
    address: "3003 Beverly Hills Dr",
    city: "Beverly Hills",
    state: "CA",
    zip: "90210",
    price: "$2,500,000",
    beds: 5,
    baths: 4,
    sqft: 3500,
    status: "Active",
    mlsId: "MLSCA0003",
    salesPitch: "Luxurious 5-bedroom mansion in prestigious Beverly Hills. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "4004 Hollywood Blvd",
    city: "Hollywood",
    state: "CA",
    zip: "90028",
    price: "$950,000",
    beds: 3,
    baths: 2,
    sqft: 1900,
    status: "Active",
    mlsId: "MLSCA0004",
    salesPitch: "Charming 3-bedroom home in the heart of Hollywood! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining."
  },
  {
    address: "5005 Malibu Beach Rd",
    city: "Malibu",
    state: "CA",
    zip: "90265",
    price: "$3,200,000",
    beds: 4,
    baths: 3,
    sqft: 2800,
    status: "Pending",
    mlsId: "MLSCA0005",
    salesPitch: "Stunning beachfront property with panoramic ocean views. Modern design with high-end finishes throughout."
  },
  {
    address: "6006 Palo Alto Ave",
    city: "Palo Alto",
    state: "CA",
    zip: "94301",
    price: "$2,100,000",
    beds: 4,
    baths: 3,
    sqft: 2400,
    status: "Active",
    mlsId: "MLSCA0006",
    salesPitch: "Modern 4-bedroom home in Silicon Valley. Perfect for tech professionals, close to major companies."
  },
  {
    address: "7007 Sacramento St",
    city: "Sacramento",
    state: "CA",
    zip: "95814",
    price: "$750,000",
    beds: 3,
    baths: 2,
    sqft: 1800,
    status: "Active",
    mlsId: "MLSCA0007",
    salesPitch: "Beautiful 3-bedroom home in the capital city. Great for families, close to schools and parks."
  },
  {
    address: "8008 San Diego Bay Dr",
    city: "San Diego",
    state: "CA",
    zip: "92101",
    price: "$1,400,000",
    beds: 3,
    baths: 2,
    sqft: 2100,
    status: "Active",
    mlsId: "MLSCA0008",
    salesPitch: "Waterfront condo with stunning bay views. Modern amenities and prime location in downtown San Diego."
  },
  {
    address: "9009 Oakland Hills Rd",
    city: "Oakland",
    state: "CA",
    zip: "94611",
    price: "$1,100,000",
    beds: 4,
    baths: 3,
    sqft: 2300,
    status: "Pending",
    mlsId: "MLSCA0009",
    salesPitch: "Charming hillside home with city views. Recently renovated with modern finishes."
  },
  {
    address: "1010 Fresno Ave",
    city: "Fresno",
    state: "CA",
    zip: "93721",
    price: "$450,000",
    beds: 3,
    baths: 2,
    sqft: 1600,
    status: "Active",
    mlsId: "MLSCA0010",
    salesPitch: "Affordable 3-bedroom home in central California. Great starter home with potential for expansion."
  },
  // Massachusetts
  {
    address: "10 Beacon St",
    city: "Boston",
    state: "MA",
    zip: "02108",
    price: "$950,000",
    beds: 3,
    baths: 2,
    sqft: 1600,
    status: "Active",
    mlsId: "MLSMA0001",
    salesPitch: "Charming 3-bedroom home in the heart of Boston! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "20 Main St",
    city: "Cambridge",
    state: "MA",
    zip: "02139",
    price: "$1,100,000",
    beds: 4,
    baths: 3,
    sqft: 2100,
    status: "Active",
    mlsId: "MLSMA0002",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  {
    address: "30 Commonwealth Ave",
    city: "Boston",
    state: "MA",
    zip: "02116",
    price: "$1,350,000",
    beds: 3,
    baths: 2,
    sqft: 1800,
    status: "Pending",
    mlsId: "MLSMA0003",
    salesPitch: "Elegant Back Bay brownstone with historic charm and modern amenities. Prime location near parks and shopping."
  },
  {
    address: "40 Harvard St",
    city: "Cambridge",
    state: "MA",
    zip: "02138",
    price: "$1,200,000",
    beds: 4,
    baths: 3,
    sqft: 2200,
    status: "Active",
    mlsId: "MLSMA0004",
    salesPitch: "Beautiful home near Harvard University. Perfect for academics or professionals, close to campus and transit."
  },
  {
    address: "50 Newbury St",
    city: "Boston",
    state: "MA",
    zip: "02116",
    price: "$1,750,000",
    beds: 2,
    baths: 2,
    sqft: 1400,
    status: "Active",
    mlsId: "MLSMA0005",
    salesPitch: "Luxury condo on prestigious Newbury Street. High-end finishes and prime shopping location."
  },
  {
    address: "60 Salem St",
    city: "Salem",
    state: "MA",
    zip: "01970",
    price: "$650,000",
    beds: 3,
    baths: 2,
    sqft: 1700,
    status: "Active",
    mlsId: "MLSMA0006",
    salesPitch: "Historic home in charming Salem. Rich history and modern updates, close to waterfront and attractions."
  },
  {
    address: "70 Cape Cod Dr",
    city: "Hyannis",
    state: "MA",
    zip: "02601",
    price: "$850,000",
    beds: 4,
    baths: 3,
    sqft: 2000,
    status: "Active",
    mlsId: "MLSMA0007",
    salesPitch: "Beautiful Cape Cod home near the beach. Perfect summer retreat with classic New England charm."
  },
  {
    address: "80 Worcester Ave",
    city: "Worcester",
    state: "MA",
    zip: "01604",
    price: "$425,000",
    beds: 3,
    baths: 2,
    sqft: 1500,
    status: "Active",
    mlsId: "MLSMA0008",
    salesPitch: "Affordable 3-bedroom home in central Massachusetts. Great value with potential for customization."
  },
  {
    address: "90 Springfield Rd",
    city: "Springfield",
    state: "MA",
    zip: "01103",
    price: "$375,000",
    beds: 3,
    baths: 2,
    sqft: 1400,
    status: "Pending",
    mlsId: "MLSMA0009",
    salesPitch: "Charming home in historic Springfield. Great starter home with room to grow."
  },
  {
    address: "100 Lowell St",
    city: "Lowell",
    state: "MA",
    zip: "01854",
    price: "$500,000",
    beds: 3,
    baths: 2,
    sqft: 1600,
    status: "Active",
    mlsId: "MLSMA0010",
    salesPitch: "Well-maintained home in revitalized Lowell. Close to Boston with small-town charm."
  },
  // Florida
  {
    address: "101 Ocean Dr",
    city: "Miami Beach",
    state: "FL",
    zip: "33139",
    price: "$2,200,000",
    beds: 5,
    baths: 4,
    sqft: 3200,
    status: "Active",
    mlsId: "MLSFL0001",
    salesPitch: "Modern 5-bedroom home in a prime location. Close to downtown, parks, and public transportation. Perfect for first-time homebuyers or investors."
  },
  {
    address: "202 Gulf Blvd",
    city: "Clearwater",
    state: "FL",
    zip: "33767",
    price: "$1,500,000",
    beds: 4,
    baths: 3,
    sqft: 2500,
    status: "Pending",
    mlsId: "MLSFL0002",
    salesPitch: "Beautifully maintained 4-bedroom home with modern finishes throughout. Features a gourmet kitchen, large master suite, and a private backyard oasis. Move-in ready!"
  },
  // ... 23 more for FL ...
  // Louisiana
  {
    address: "100 Bourbon St",
    city: "New Orleans",
    state: "LA",
    zip: "70116",
    price: "$850,000",
    beds: 3,
    baths: 2,
    sqft: 1700,
    status: "Active",
    mlsId: "MLSLA0001",
    salesPitch: "Charming 3-bedroom home in the heart of New Orleans! Enjoy an open floor plan, updated kitchen, and a spacious backyard perfect for entertaining. Walk to shops, parks, and restaurants!"
  },
  {
    address: "200 Canal St",
    city: "New Orleans",
    state: "LA",
    zip: "70130",
    price: "$1,200,000",
    beds: 4,
    baths: 3,
    sqft: 2100,
    status: "Active",
    mlsId: "MLSLA0002",
    salesPitch: "Luxurious 4-bedroom home with a modern design. Features a gourmet kitchen, large master suite, and a spacious backyard."
  },
  // ... 23 more for LA ...
  // --- END GENERATED MOCK PROPERTIES ---
];

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const address = searchParams.get('address')?.toLowerCase() || "";
  const query = searchParams.get('query')?.toLowerCase() || "";

  // Use either address or query parameter
  const searchTerm = address || query;

  // If no search term provided, return all properties
  if (!searchTerm) {
    return NextResponse.json({ results: mockMLSData });
  }

  // Simulate search by address, city, or state
  const result = mockMLSData.filter((item) => {
    const fullAddress = `${item.address}, ${item.city}, ${item.state} ${item.zip}`.toLowerCase();
    
    // Check if search term matches any part of the address
    if (fullAddress.includes(searchTerm)) {
      return true;
    }
    
    // Also check individual fields for better matching
    if (item.city.toLowerCase().includes(searchTerm) || 
        item.state.toLowerCase().includes(searchTerm) ||
        item.address.toLowerCase().includes(searchTerm)) {
      return true;
    }
    
    return false;
  });

  return NextResponse.json({ results: result });
} 